# Generated by Django 2.0.7 on 2018-07-31 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=250)),
                ('description_categorie', models.CharField(max_length=1000)),
                ('logo_categorie', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etudiant', models.CharField(max_length=100)),
                ('prenom_etudiant', models.CharField(max_length=100)),
                ('date_naiss', models.DateField()),
                ('cin_etudiant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_event', models.CharField(max_length=250)),
                ('description_event', models.CharField(max_length=1000)),
                ('date_event', models.DateTimeField()),
                ('logo_event', models.CharField(max_length=1000)),
                ('is_favorite', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Categorie')),
            ],
        ),
    ]
